name: موقع ملهم|شغف المعرفة
url: https://mulham.github.io
markdown: kramdown
permalink: /:title
timezone: Asia/Damascus
defaults:
 scope:
 path: "" # an empty string here means all files in the project
 values:
encoding: "utf-8"
paginate: 5
paginate_path: /page:num
excerpt_separator: <!--more-->
gems: [jekyll-sitemap, jekyll-paginate]

